import { db } from '../src/lib/db';
import { users, profiles, jobs } from '../src/lib/db/schema';

async function seed() {
  console.log('🌱 Seeding database...');

  // Create 3 users with profiles
  const user1 = await db.insert(users).values({
    email: 'john.doe@example.com',
  }).returning();

  await db.insert(profiles).values({
    userId: user1[0].id,
    cvFilename: 'john_doe_cv.pdf',
    cvRawText: 'Experienced software engineer...',
    yearsExperience: '5-9',
    educationLevel: 'Bachelors',
    fieldOfStudy: 'STEM',
    sphereOfExpertise: 'Engineering',
    seniorityLevel: 'Senior',
    industry: 'Technology',
    languages: ['English', 'Spanish'],
    keySkills: ['JavaScript', 'React', 'Node.js', 'TypeScript'],
    prefEmploymentType: ['Full-time'],
    prefWorkMode: 'Remote',
    prefSalaryMin: 80000,
    prefSalaryMax: 120000,
    prefSalaryCurrency: 'USD',
  });

  const user2 = await db.insert(users).values({
    email: 'jane.smith@example.com',
  }).returning();

  await db.insert(profiles).values({
    userId: user2[0].id,
    cvFilename: 'jane_smith_cv.pdf',
    cvRawText: 'Marketing specialist with MBA...',
    yearsExperience: '2-4',
    educationLevel: 'Masters',
    fieldOfStudy: 'Business & Economics',
    sphereOfExpertise: 'Marketing',
    seniorityLevel: 'Mid',
    industry: 'Retail & E-commerce',
    languages: ['English', 'French'],
    keySkills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics'],
    prefEmploymentType: ['Full-time', 'Part-time'],
    prefWorkMode: 'Hybrid',
  });

  const user3 = await db.insert(users).values({
    email: 'alex.johnson@example.com',
  }).returning();

  await db.insert(profiles).values({
    userId: user3[0].id,
    cvFilename: 'alex_johnson_cv.pdf',
    cvRawText: 'Data scientist with PhD in Statistics...',
    yearsExperience: '10-15',
    educationLevel: 'PhD',
    fieldOfStudy: 'STEM',
    sphereOfExpertise: 'Data Science',
    seniorityLevel: 'Lead/Manager',
    industry: 'Finance & Banking',
    languages: ['English', 'German', 'Mandarin'],
    keySkills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'PyTorch'],
    prefEmploymentType: ['Full-time'],
    prefWorkMode: 'Any',
    prefRelocation: true,
    prefSalaryMin: 150000,
    prefSalaryMax: 200000,
    prefSalaryCurrency: 'USD',
  });

  // Create 50 jobs across different industries and seniority levels
  const jobsData = [
    // Technology - 15 jobs
    {
      externalId: 'tech-001',
      source: 'adzuna',
      title: 'Senior Software Engineer',
      company: 'TechCorp',
      location: 'San Francisco, CA',
      country: 'USA',
      url: 'https://example.com/job/tech-001',
      descriptionRaw: 'Looking for experienced software engineer...',
      salaryMin: 120000,
      salaryMax: 160000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '5-9',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Engineering',
      seniorityLevel: 'Senior',
      industry: 'Technology',
      languages: ['English'],
      keySkills: ['JavaScript', 'React', 'Node.js'],
    },
    {
      externalId: 'tech-002',
      source: 'jooble',
      title: 'Junior Frontend Developer',
      company: 'StartupXYZ',
      location: 'Remote',
      country: 'USA',
      url: 'https://example.com/job/tech-002',
      descriptionRaw: 'Entry-level frontend position...',
      salaryMin: 60000,
      salaryMax: 80000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '0-1',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Engineering',
      seniorityLevel: 'Junior',
      industry: 'Technology',
      languages: ['English'],
      keySkills: ['HTML', 'CSS', 'JavaScript', 'React'],
    },
    {
      externalId: 'tech-003',
      source: 'eures',
      title: 'Lead Data Scientist',
      company: 'AI Innovations',
      location: 'London, UK',
      country: 'UK',
      url: 'https://example.com/job/tech-003',
      descriptionRaw: 'Leading data science team...',
      salaryMin: 100000,
      salaryMax: 140000,
      salaryCurrency: 'GBP',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '10-15',
      educationLevel: 'PhD',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Data Science',
      seniorityLevel: 'Lead/Manager',
      industry: 'Technology',
      languages: ['English'],
      keySkills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL'],
    },
    {
      externalId: 'tech-004',
      source: 'adzuna',
      title: 'DevOps Engineer',
      company: 'CloudTech',
      location: 'Berlin, Germany',
      country: 'Germany',
      url: 'https://example.com/job/tech-004',
      descriptionRaw: 'DevOps engineer for cloud infrastructure...',
      salaryMin: 70000,
      salaryMax: 95000,
      salaryCurrency: 'EUR',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '2-4',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'IT/DevOps',
      seniorityLevel: 'Mid',
      industry: 'Technology',
      languages: ['English', 'German'],
      keySkills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    },
    {
      externalId: 'tech-005',
      source: 'jooble',
      title: 'Product Manager',
      company: 'SaaS Solutions',
      location: 'Austin, TX',
      country: 'USA',
      url: 'https://example.com/job/tech-005',
      descriptionRaw: 'Product management role for B2B SaaS...',
      salaryMin: 110000,
      salaryMax: 150000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '5-9',
      educationLevel: 'Masters',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Product',
      seniorityLevel: 'Senior',
      industry: 'Technology',
      languages: ['English'],
      keySkills: ['Product Strategy', 'Agile', 'User Research', 'Analytics'],
    },
    // Unclassified tech jobs
    {
      externalId: 'tech-006',
      source: 'adzuna',
      title: 'Full Stack Developer',
      company: 'WebDev Co',
      location: 'New York, NY',
      country: 'USA',
      url: 'https://example.com/job/tech-006',
      descriptionRaw: 'Full stack development position...',
      salaryMin: 90000,
      salaryMax: 130000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: false,
    },
    {
      externalId: 'tech-007',
      source: 'jooble',
      title: 'Mobile App Developer',
      company: 'AppMakers',
      location: 'Seattle, WA',
      country: 'USA',
      url: 'https://example.com/job/tech-007',
      descriptionRaw: 'iOS and Android development...',
      salaryMin: 95000,
      salaryMax: 135000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
    },
    {
      externalId: 'tech-008',
      source: 'eures',
      title: 'UX Designer',
      company: 'Design Studio',
      location: 'Amsterdam, Netherlands',
      country: 'Netherlands',
      url: 'https://example.com/job/tech-008',
      descriptionRaw: 'User experience design role...',
      employmentType: 'Contract',
      isRemote: true,
    },
    {
      externalId: 'tech-009',
      source: 'adzuna',
      title: 'QA Engineer',
      company: 'TestCorp',
      location: 'Toronto, Canada',
      country: 'Canada',
      url: 'https://example.com/job/tech-009',
      descriptionRaw: 'Quality assurance testing...',
      salaryMin: 70000,
      salaryMax: 90000,
      salaryCurrency: 'CAD',
      employmentType: 'Full-time',
      isRemote: false,
    },
    {
      externalId: 'tech-010',
      source: 'jooble',
      title: 'Security Engineer',
      company: 'SecureTech',
      location: 'Paris, France',
      country: 'France',
      url: 'https://example.com/job/tech-010',
      descriptionRaw: 'Cybersecurity position...',
      employmentType: 'Full-time',
      isRemote: true,
    },

    // Finance & Banking - 10 jobs
    {
      externalId: 'fin-001',
      source: 'adzuna',
      title: 'Senior Financial Analyst',
      company: 'BigBank Corp',
      location: 'New York, NY',
      country: 'USA',
      url: 'https://example.com/job/fin-001',
      descriptionRaw: 'Financial analysis and modeling...',
      salaryMin: 100000,
      salaryMax: 140000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '5-9',
      educationLevel: 'Masters',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Finance',
      seniorityLevel: 'Senior',
      industry: 'Finance & Banking',
      languages: ['English'],
      keySkills: ['Financial Modeling', 'Excel', 'SQL', 'Risk Analysis'],
    },
    {
      externalId: 'fin-002',
      source: 'jooble',
      title: 'Quantitative Analyst',
      company: 'Hedge Fund Alpha',
      location: 'London, UK',
      country: 'UK',
      url: 'https://example.com/job/fin-002',
      descriptionRaw: 'Quantitative trading strategies...',
      salaryMin: 120000,
      salaryMax: 180000,
      salaryCurrency: 'GBP',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '5-9',
      educationLevel: 'PhD',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Data Science',
      seniorityLevel: 'Senior',
      industry: 'Finance & Banking',
      languages: ['English'],
      keySkills: ['Python', 'Statistics', 'C++', 'Machine Learning'],
    },
    {
      externalId: 'fin-003',
      source: 'eures',
      title: 'Risk Manager',
      company: 'Insurance Giant',
      location: 'Zurich, Switzerland',
      country: 'Switzerland',
      url: 'https://example.com/job/fin-003',
      descriptionRaw: 'Enterprise risk management...',
      salaryMin: 110000,
      salaryMax: 150000,
      salaryCurrency: 'CHF',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '10-15',
      educationLevel: 'Masters',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Finance',
      seniorityLevel: 'Lead/Manager',
      industry: 'Finance & Banking',
      languages: ['English', 'German', 'French'],
      keySkills: ['Risk Management', 'Compliance', 'Analytics', 'Reporting'],
    },
    // Unclassified finance jobs
    {
      externalId: 'fin-004',
      source: 'adzuna',
      title: 'Investment Banking Analyst',
      company: 'Elite Bank',
      location: 'Hong Kong',
      country: 'Hong Kong',
      url: 'https://example.com/job/fin-004',
      descriptionRaw: 'M&A and corporate finance...',
      employmentType: 'Full-time',
      isRemote: false,
    },
    {
      externalId: 'fin-005',
      source: 'jooble',
      title: 'Accountant',
      company: 'Accounting Firm',
      location: 'Dublin, Ireland',
      country: 'Ireland',
      url: 'https://example.com/job/fin-005',
      descriptionRaw: 'General accounting duties...',
      salaryMin: 50000,
      salaryMax: 70000,
      salaryCurrency: 'EUR',
      employmentType: 'Full-time',
      isRemote: false,
    },

    // Healthcare - 8 jobs
    {
      externalId: 'health-001',
      source: 'adzuna',
      title: 'Registered Nurse',
      company: 'City Hospital',
      location: 'Boston, MA',
      country: 'USA',
      url: 'https://example.com/job/health-001',
      descriptionRaw: 'RN position in emergency department...',
      salaryMin: 70000,
      salaryMax: 90000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '2-4',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'Medicine & Health',
      sphereOfExpertise: 'Healthcare',
      seniorityLevel: 'Mid',
      industry: 'Healthcare',
      languages: ['English'],
      keySkills: ['Patient Care', 'Emergency Medicine', 'Clinical Skills'],
    },
    {
      externalId: 'health-002',
      source: 'jooble',
      title: 'Medical Director',
      company: 'HealthTech Solutions',
      location: 'Remote',
      country: 'USA',
      url: 'https://example.com/job/health-002',
      descriptionRaw: 'Lead clinical operations...',
      salaryMin: 200000,
      salaryMax: 280000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '15+',
      educationLevel: 'PhD',
      fieldOfStudy: 'Medicine & Health',
      sphereOfExpertise: 'Healthcare',
      seniorityLevel: 'Director+',
      industry: 'Healthcare',
      languages: ['English'],
      keySkills: ['Clinical Leadership', 'Healthcare Management', 'Medical Strategy'],
    },
    // Unclassified healthcare jobs
    {
      externalId: 'health-003',
      source: 'eures',
      title: 'Physical Therapist',
      company: 'Rehab Center',
      location: 'Stockholm, Sweden',
      country: 'Sweden',
      url: 'https://example.com/job/health-003',
      descriptionRaw: 'Physical therapy services...',
      employmentType: 'Full-time',
      isRemote: false,
    },

    // Retail & E-commerce - 7 jobs
    {
      externalId: 'retail-001',
      source: 'adzuna',
      title: 'E-commerce Manager',
      company: 'Online Retail Co',
      location: 'Los Angeles, CA',
      country: 'USA',
      url: 'https://example.com/job/retail-001',
      descriptionRaw: 'Manage online sales channel...',
      salaryMin: 80000,
      salaryMax: 110000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '5-9',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Marketing',
      seniorityLevel: 'Senior',
      industry: 'Retail & E-commerce',
      languages: ['English'],
      keySkills: ['E-commerce', 'Digital Marketing', 'Analytics', 'SEO'],
    },
    {
      externalId: 'retail-002',
      source: 'jooble',
      title: 'Supply Chain Analyst',
      company: 'Global Retailer',
      location: 'Atlanta, GA',
      country: 'USA',
      url: 'https://example.com/job/retail-002',
      descriptionRaw: 'Supply chain optimization...',
      salaryMin: 65000,
      salaryMax: 85000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '2-4',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Operations',
      seniorityLevel: 'Mid',
      industry: 'Retail & E-commerce',
      languages: ['English'],
      keySkills: ['Supply Chain', 'Logistics', 'Data Analysis', 'Excel'],
    },
    // Unclassified retail jobs
    {
      externalId: 'retail-003',
      source: 'eures',
      title: 'Store Manager',
      company: 'Fashion Retail',
      location: 'Milan, Italy',
      country: 'Italy',
      url: 'https://example.com/job/retail-003',
      descriptionRaw: 'Manage retail location...',
      employmentType: 'Full-time',
      isRemote: false,
    },

    // Consulting - 5 jobs
    {
      externalId: 'consult-001',
      source: 'adzuna',
      title: 'Management Consultant',
      company: 'Big Four Firm',
      location: 'Chicago, IL',
      country: 'USA',
      url: 'https://example.com/job/consult-001',
      descriptionRaw: 'Strategy consulting projects...',
      salaryMin: 90000,
      salaryMax: 130000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '2-4',
      educationLevel: 'Masters',
      fieldOfStudy: 'Business & Economics',
      sphereOfExpertise: 'Consulting',
      seniorityLevel: 'Mid',
      industry: 'Consulting',
      languages: ['English'],
      keySkills: ['Strategy', 'Business Analysis', 'PowerPoint', 'Client Management'],
    },
    {
      externalId: 'consult-002',
      source: 'jooble',
      title: 'Senior IT Consultant',
      company: 'Tech Consulting',
      location: 'Remote',
      country: 'USA',
      url: 'https://example.com/job/consult-002',
      descriptionRaw: 'IT transformation consulting...',
      salaryMin: 110000,
      salaryMax: 150000,
      salaryCurrency: 'USD',
      employmentType: 'Full-time',
      isRemote: true,
      yearsExperience: '5-9',
      educationLevel: 'Bachelors',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Consulting',
      seniorityLevel: 'Senior',
      industry: 'Consulting',
      languages: ['English'],
      keySkills: ['IT Strategy', 'Cloud Migration', 'Change Management', 'Agile'],
    },

    // Education - 5 jobs
    {
      externalId: 'edu-001',
      source: 'eures',
      title: 'University Professor',
      company: 'State University',
      location: 'Oxford, UK',
      country: 'UK',
      url: 'https://example.com/job/edu-001',
      descriptionRaw: 'Tenure-track faculty position...',
      salaryMin: 60000,
      salaryMax: 90000,
      salaryCurrency: 'GBP',
      employmentType: 'Full-time',
      isRemote: false,
      yearsExperience: '10-15',
      educationLevel: 'PhD',
      fieldOfStudy: 'STEM',
      sphereOfExpertise: 'Education',
      seniorityLevel: 'Lead/Manager',
      industry: 'Education',
      languages: ['English'],
      keySkills: ['Research', 'Teaching', 'Publishing', 'Grant Writing'],
    },
    // Unclassified education jobs
    {
      externalId: 'edu-002',
      source: 'adzuna',
      title: 'High School Teacher',
      company: 'Public School District',
      location: 'Portland, OR',
      country: 'USA',
      url: 'https://example.com/job/edu-002',
      descriptionRaw: 'Mathematics teacher...',
      employmentType: 'Full-time',
      isRemote: false,
    },
  ];

  for (const job of jobsData) {
    await db.insert(jobs).values(job);
  }

  console.log('✅ Seeding complete!');
  console.log(`Created 3 users with profiles`);
  console.log(`Created ${jobsData.length} jobs`);
  
  process.exit(0);
}

seed().catch((error) => {
  console.error('❌ Seeding failed:', error);
  process.exit(1);
});
